/// <reference types="react-scripts" />
declare module 'styled-components/macro'; // because the typings were causing a clash with react-native types for some reason...
declare module 'react-particles-webgl';